=== hb-liugx/simulator/conf/command.dtd
<!ELEMENT command (output, parameters?)>
<!ELEMENT output (successful, failed)>
<!ELEMENT parameters (parameter+)>
<!ELEMENT successful (#PCDATA)>
<!ELEMENT failed (#PCDATA)>
<!ELEMENT parameter EMPTY>
<!ATTLIST command name CDATA #REQUIRED
                  description CDATA #REQUIRED
                  endpoint CDATA #REQUIRED
                  method (GET | SET | PUT | DELETE | POST ) "GET"
                  persistence (true | false) "false"
                  storageName CDATA ""
                  class CDATA "">
<!ATTLIST successful type (text | file | json ) "json"
                     httpcode CDATA "200"
                     class CDATA "">
<!ATTLIST failed type (text | file  | json ) "json"
                 httpcode CDATA "401">
<!ATTLIST parameter name CDATA #REQUIRED
                    objectName CDATA #REQUIRED
                    isKey (true | false) "false"
                    comparable (true | false) "false"   
                    sessional (true | false) "false">

=== hb-liugx/simulator/conf/command/hs_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Sets the global Hyperserver configuration." name="set global hyperserver configuration" 
         method="POST" endpoint="peaxy/conf/hs/set" persistence="true" storageName="conf_hs" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandHS">
	<output>
		<successful type="json">successful</successful>
		<failed type="text">failed</failed>
	</output>
	<parameters>
		<parameter name="cardinality"/>
		<parameter name="spare_count"/>
		<parameter name="member_replacement"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/rule_getfilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Returns one or more ingest policies that match the getfilter criteria." name="get filter for configuration rule" 
         method="PUT" endpoint="conf/rule/getfilter" persistence="true" storageName="rule_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandRule">
	<output>
		<successful type="json">Success</successful>
		<failed type="text">failure</failed>
	</output>
    <parameters>
        <parameter name="id"/>
        <parameter name="group_id"/>
        <parameter name="parent_path"/>      
    </parameters>
</command>

=== hb-liugx/simulator/conf/command/stats_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Sets the statistics that will be collected by the Hyperserver." name="set statistics configuration" 
         method="POST" endpoint="peaxy/conf/stats/set" persistence="true" storageName="stats_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandStats">
	<output>
		<successful type="json">successful</successful>
		<failed type="text">failed</failed>
	</output>
    <parameters>
        <parameter name="interval"/>
        <parameter name="server_ip"/>
        <parameter name="server_port"/>
        <parameter name="enabled_stats"/>
    </parameters>
</command>

=== hb-liugx/simulator/conf/command/email_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Sets the email configuration used by Hyperserver administrators." name="set email configuration" 
         method="POST" endpoint="peaxy/conf/email/set" persistence="true" storageName="conf_email" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandEmail">
	<output>
		<successful type="json">successful</successful>
		<failed type="text">failed</failed>
	</output>
	<parameters>
		<parameter name="login"/>
		<parameter name="protocol"/>
		<parameter name="server"/>
		<parameter name="port"/>
		<parameter name="password"/>
		<parameter name="from"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/ntp_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="If an NTP server will be used for this Hyperserver, sets the NTP servers and the time zone." name="set NTP configuration" 
         method="POST" endpoint="peaxy/conf/ntp/set" persistence="true" storageName="conf_ntp" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandNTP">
	<output>
		<successful type="json">successful</successful>
		<failed type="text">failed</failed>
	</output>
	<parameters>
		<parameter name="server1"/>
		<parameter name="server2"/>
		<parameter name="server3"/>
		<parameter name="time_zone"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/rule_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Sets a configuration rule." name="set configuration rule" 
         method="PUT" endpoint="conf/rule/set" persistence="true" storageName="rule_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandRule">
	<output>
		<successful type="json">Success</successful>
		<failed type="text">failure</failed>
	</output>
    <parameters>
        <parameter name="id"/>
        <parameter name="name"/>
        <parameter name="group_id"/>
        <parameter name="prefix"/>
        <parameter name="suffix"/>
        <parameter name="recursive"/>
        <parameter name="sc_id"/>
        <parameter name="RuleFlag"/>        
    </parameters>
</command>

=== hb-liugx/simulator/conf/command/dns_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Sets the DNS configuration for the Hyperfiler." name="set DNS configuration" 
         method="POST" endpoint="peaxy/conf/dns/set" persistence="true" storageName="conf_dns" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandDNS">
	<output>
		<successful type="text">successful</successful>
		<failed type="text">failed</failed>
	</output>
	<parameters>
		<parameter name="domain"/>
		<parameter name="srv1"/>
		<parameter name="srv2"/>
		<parameter name="srv3"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/stats_get.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "../command.dtd">

<command description="Gets the current statistics that are collected for the Hyperserver." name="get statistics configuration" 
         method="GET" endpoint="peaxy/conf/stats/get" persistence="false" storageName="stats_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandStats">
	<output>
		<successful type="json">successful</successful>
		<failed type="text">failed</failed>
	</output>
	<parameters>
        <parameter name="interval"/>
        <parameter name="server_ip"/>
        <parameter name="server_port"/>
        <parameter name="enabled_stats"/>
    </parameters>
</command>
