=== hb-liugx/simulator/conf/command.dtd
<!ELEMENT command (output, parameters?)>
<!ELEMENT output (successful, failed)>
<!ELEMENT parameters (parameter+)>
<!ELEMENT successful (#PCDATA)>
<!ELEMENT failed (#PCDATA)>
<!ELEMENT parameter EMPTY>
<!ATTLIST command name CDATA #REQUIRED
                  description CDATA #REQUIRED
                  endpoint CDATA #REQUIRED
                  method (GET | SET | PUT | DELETE | POST ) "GET"
                  persistence (true | false) "false"
                  storageName CDATA ""
                  class CDATA "">
<!ATTLIST successful type (text | file | json ) "json"
                     httpcode CDATA "200"
                     class CDATA "">
<!ATTLIST failed type (text | file  | json ) "json"
                 httpcode CDATA "401">
<!ATTLIST parameter name CDATA #REQUIRED
                    objectName CDATA #REQUIRED
                    isKey (true | false) "false"
                    comparable (true | false) "false"   
                    sessional (true | false) "false">

=== hb-liugx/simulator/conf/command/rule_create.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Creates new or modify existing ingest policies." name="create configuration rule" 
         method="PUT" endpoint="conf/rule/create" persistence="true" storageName="rule_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandRule">
	<output>
		<successful type="json">Success</successful>
		<failed type="text">failure</failed>
	</output>
	<parameters>
		<parameter name="parent_path"/>
		<parameter name="recursive"/>
		<parameter name="group_id"/>
		<parameter name="file_type"/>
		<parameter name="sc_id"/>
		<parameter name="name"/>
		<parameter name="id"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/sc_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Configures a new Storage Class within a Hyperfiler." name="set storage class" 
         method="PUT" endpoint="conf/sc/set" persistence="true" storageName="sc_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandSC">
	<output>
		<successful type="json">Success</successful>
		<failed type="text">failure</failed>
	</output>
    <parameters>
        <parameter name="id"/>
        <parameter name="name"/>
        <parameter name="description"/>
        <parameter name="list"/>
        <parameter name="cardinality"/>
        <parameter name="capacity"/>
        <parameter name="device_type"/>
    </parameters>
</command>

=== hb-liugx/simulator/conf/command/use_update.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Updates a user password." name="update user password" method="POST" 
         endpoint="aaa/user/updatepwd" persistence="true" storageName="user" class="">
    <output>
        <successful type="text">Success</successful>
        <failed type="text">failure</failed>
    </output>
    <parameters>
        <parameter isKey="true" name="name"/>
        <parameter name="oldpassword"/>
        <parameter name="newpassword"/>
    </parameters>
</command>

=== hb-liugx/simulator/conf/command/user_create.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Creates a user account. The initial Administrator account is created during the setup. That user can create other administrator users as needed." 
         name="create user" method="PUT" endpoint="aaa/user/create" persistence="true" storageName="user" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandCreateUser">
	<output>
		<successful type="json">Success</successful>
		<failed type="text">failure</failed>
	</output>
	<parameters>
		<parameter isKey="true" name="name"/>
		<parameter name="password"/>
		<parameter name="email"/>
		<parameter name="role"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/sc_create.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Creates a new storage class." name="storage class create" 
         method="POST" endpoint="conf/sc/create" persistence="true" storageName="sc_conf" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandSC">
	<output>
		<successful type="json">Success</successful>
		<failed type="text">failure</failed>
	</output>
	<parameters>
		<parameter name="name"/>
		<parameter name="description"/>
		<parameter name="list"/>
		<parameter name="cardinality"/>
		<parameter name="capacity"/>
		<parameter name="device_type"/>
	</parameters>
</command>

=== hb-liugx/simulator/conf/command/log_set.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "conf/command.dtd">

<command description="Creates or updates the existing logging configuration." name="set log configuration" 
         method="PUT" endpoint="peaxy/conf/log/set" persistence="true" storageName="conf_log" 
         class="net.peaxy.simulator.entity.PredefinedRESTCommandLog">
	<output>
		<successful type="json">successful</successful>
		<failed type="text">failed</failed>
	</output>
	<parameters>
		<parameter name="includes" objectName="filter_list"/>
		<parameter name="enable_syslog" objectName="filter_list"/>
		<parameter name="level" objectName="filter_list"/>
        <parameter name="port"/>
        <parameter name="log_server"/>
	</parameters>
</command>
